# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  boot:
    name: Bootstrap
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Add lerna Global
        run: yarn global add lerna
      
      - name: Clean & Install Deps
        run: yarn boot
          
  build:
    name: Build
    needs: boot
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Build Docz
        working-directory: ./packages/flash-components-docs
        run: yarn build

  deploy:
    name: Deploy
    needs: build
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Deploy to Now
        working-directory: ./packages/flash-components-docs/out
        env:
          NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
        run: now --token ${NOW_TOKEN} --confirm --name flash-components --no-clipboard --prod
