# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deployment
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node JS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      
      - name: Bootstrap Project
        run: |
          yarn global add lerna
          yarn boot

      - name: Build Docz
        working-directory: ./packages/flash-components-docs
        run: yarn build
        
      - name: Deploy to Now
        working-directory: ./packages/flash-components-docs/out
        run: |
          yarn global add now@latest
          now --token ${{ secrets.NOW_TOKEN }}
